### ISSUE TITLE
Reconstructed Dataset in ReID Style

### ISSUE THREAD

**Issue by KeepRunning2023** [yqc123456/HKD_for_person_search#2]
Hello, thank you for sharing your work. 
Could you share your reconstructed person Re-ID dataset from G2APS? I do not find the download link in [Running_instruction.md](https://github.com/yqc123456/HKD_for_person_search/blob/main/Running_instruction.md)
If you could help, I will appreciate very much. Look forward to your reply. : )

**Comment by yqc123456** [comment]
Thansks for appreciation.
I am a bittle busy these days,
and I will upload the reid version to disk and provide the link to you in
some days.

KeepRunning ***@***.***> 于2024年2月27日周二 11:40写道：

**Comment by KeepRunning2023** [comment]
Thank you very much! Looking forward to hearing from you.

**Comment by yqc123456** [comment]
Sorry to keep you waiting. You can now download the ReID version of the dataset under the name G2APS_in_market1501_style.zip

**Comment by KeepRunning2023** [comment]
Thank you very much for sharing the dataset. However, while analyzing the dataset, I noticed that the training dataset is missing the images with ID 1609. I would like to kindly request the authors to verify whether this is an error on my part or if the images is indeed missing from the dataset. Thanks.
